services:
  jupyterlab:
    build: .
    container_name: jupyter_datascience_lsp
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: "0.80"
